import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto } from "next/font/google";
import "../globals.css";
import Menu from "@/components/Menu/Menu";
import Header from "@/components/Menu/Header";
// import cn from "classnames";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  // const useZeroPadding = false;
  // const mainClassName = cn(
  //   "bg-[#fff] h-full rounded-[1rem] shadow-2xl px-[3rem] py-[2.5rem] border-[1px] border-[#F6F6F6] overflow-hidden",
  //   {
  //     "pt-[0]": useZeroPadding,
  //   }
  // );

  return (
    <html lang="en" className="overflow-hidden">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${roboto.variable} antialiased`}
      >
        <div className="flex w-[100vw] h-[100vh] overflow-hidden">
          <Menu />
          <section className="flex-[1_0_auto] flex flex-col">
            <Header />
            <div className="px-[3rem] pb-[3rem] flex-[1_1_100%] bg-[linear-gradient(180deg,rgba(255,_255,_255,_1)_0%,_rgba(204,_233,_235,_1)_100%)] overflow-hidden">
              <main className="bg-[#fff] h-full rounded-[1rem] shadow-2xl border-[1px] border-[#F6F6F6] px-[.25rem] py-[.25rem] overflow-hidden">
                {/* px-[3rem] py-[2.5rem]  */}
                <div className="h-full overflow-auto px-[2.75rem] py-[2.25rem]">
                  {children}
                </div>
              </main>
            </div>
          </section>
        </div>
      </body>
    </html>
  );
};

export default RootLayout;

{
  /* <section className="bg-[red] h-full px-[3rem] pb-[3rem] rounded-[1rem] overflow-hidden">
<main className="bg-[#fff] h-full px-[3rem] py-[2.5rem] border-[1px] border-[#F6F6F6] overflow-auto shadow-2xl">
  {children}
</main>
</section> */
}

{
  /* <div className="px-[3rem] pb-[3rem] flex-[1_1_100%] bg-[linear-gradient(180deg,rgba(255,_255,_255,_1)_0%,_rgba(204,_233,_235,_1)_100%)] overflow-hidden">
<main className="bg-[#fff] h-full rounded-[1rem] shadow-2xl px-[3rem] py-[2.5rem] border-[1px] border-[#F6F6F6] overflow-auto">
  {children}
</main>
</div> */
}
